version: '3.8'

services:
  # 1. BACKEND (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume_backend
    restart: always #If container crashes → Docker restarts it
    # INJECT EVERYTHING: Passes AWS credentials, DB Host, MLflow URI, etc. automatically
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs         # Persist logs locally
      - ./models:/app/models             # Bridge for MPNet
      - ./artifacts:/app/artifacts       # Bridge for NLTK (if stored here)
    networks:
      - resume_network

  # 2. FRONTEND (Streamlit)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resume_frontend
    restart: always
    depends_on:
      - backend
    environment:
      # Specific override: Frontend needs to know where Backend is
      API_BASE_URL: "http://backend:8000"
    ports:
      - "8501:8501"
    networks:
      - resume_network

# Explicit network definition for clarity
networks:
  resume_network:
    driver: bridge
#this makes the frontend and backend container talk internally with http://backend:8000 and not http://localhost:8000 thus the internal traffic never hits the browser 
#What happens if you don’t use a custom network -- Docker will: create a default unnamed network still allow communication but this is more stable and keeps the internal traffic private and this is more scalable 