[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "resume-recommender-mlops"
version = "0.1.0"
description = "Resume recommender system with MLOps architecture"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "python-dotenv",
    "python-docx",
    "paddleocr",
    "pymupdf",
    "dvc",
    "mlflow",
    "dagshub",
    "ipykernel",
    "google-search-results",
    "requests",
    "pandas",
    "numpy",
    "beautifulsoup4",
    "lxml", 
    "tqdm",
    "python-dateutil",
    "pydantic",
    "python-dotenv",
    "langdetect",
    "unidecode",
    "nbstripout"  
]

[tool.setuptools.packages.find]
where = ["."]
