global:
  scrape_interval: 5s # Scrape every 5 seconds (Fast for local testing)

scrape_configs:
  - job_name: 'fastapi_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000'] # 'backend' matches the service name in docker-compose